# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/tandeitnik/Documents/GitHub/vivadoProjects/cfg/clocks.xdc

# XDC: C:/Users/tandeitnik/Documents/GitHub/vivadoProjects/cfg/ports.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ds_buf_1_0 || ORIG_REF_NAME==system_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_2_0/system_util_ds_buf_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ds_buf_2_0 || ORIG_REF_NAME==system_util_ds_buf_2_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_red_pitaya_adc_0_0/system_axis_red_pitaya_adc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_adc_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_adc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_red_pitaya_dac_0_0/system_axis_red_pitaya_dac_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_dac_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_dac_0_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_0/system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_125M_0/system_rst_ps7_0_125M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_125M_0 || ORIG_REF_NAME==system_rst_ps7_0_125M_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_0/system_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_0 || ORIG_REF_NAME==system_xlconstant_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_cfg_register_0_0/system_axi_cfg_register_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_cfg_register_0_0 || ORIG_REF_NAME==system_axi_cfg_register_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_1/system_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_1 || ORIG_REF_NAME==system_xlconstant_0_1} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_7/system_xlslice_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_7 || ORIG_REF_NAME==system_xlslice_0_7} -quiet] -quiet

# IP: bd/system/ip/system_dat_CHA_0/system_dat_CHA_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dat_CHA_0 || ORIG_REF_NAME==system_dat_CHA_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_8/system_xlslice_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_8 || ORIG_REF_NAME==system_xlslice_0_8} -quiet] -quiet

# IP: bd/system/ip/system_gain_a_0/system_gain_a_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_gain_a_0 || ORIG_REF_NAME==system_gain_a_0} -quiet] -quiet

# IP: bd/system/ip/system_biquadFilter_0_0/system_biquadFilter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_biquadFilter_0_0 || ORIG_REF_NAME==system_biquadFilter_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gain_a2_0/system_gain_a2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_gain_a2_0 || ORIG_REF_NAME==system_gain_a2_0} -quiet] -quiet

# IP: bd/system/ip/system_gain_b0_0/system_gain_b0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_gain_b0_0 || ORIG_REF_NAME==system_gain_b0_0} -quiet] -quiet

# IP: bd/system/ip/system_gain_b0_1/system_gain_b0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_gain_b0_1 || ORIG_REF_NAME==system_gain_b0_1} -quiet] -quiet

# IP: bd/system/ip/system_gain_b2_0/system_gain_b2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_gain_b2_0 || ORIG_REF_NAME==system_gain_b2_0} -quiet] -quiet

# IP: bd/system/ip/system_decimator_0_0/system_decimator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_decimator_0_0 || ORIG_REF_NAME==system_decimator_0_0} -quiet] -quiet

# IP: bd/system/ip/system_outputCalibration_0_0/system_outputCalibration_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_outputCalibration_0_0 || ORIG_REF_NAME==system_outputCalibration_0_0} -quiet] -quiet

# IP: bd/system/ip/system_outputCalibration_A_0/system_outputCalibration_A_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_outputCalibration_A_0 || ORIG_REF_NAME==system_outputCalibration_A_0} -quiet] -quiet

# IP: bd/system/ip/system_inputCalibration_0_0/system_inputCalibration_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_inputCalibration_0_0 || ORIG_REF_NAME==system_inputCalibration_0_0} -quiet] -quiet

# IP: bd/system/ip/system_inputCalibration_A_0/system_inputCalibration_A_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_inputCalibration_A_0 || ORIG_REF_NAME==system_inputCalibration_A_0} -quiet] -quiet

# IP: bd/system/ip/system_comparator_0_0/system_comparator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_comparator_0_0 || ORIG_REF_NAME==system_comparator_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_13/system_xlslice_0_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_13 || ORIG_REF_NAME==system_xlslice_0_13} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_14/system_xlslice_0_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_14 || ORIG_REF_NAME==system_xlslice_0_14} -quiet] -quiet

# IP: bd/system/ip/system_phaseDetector_0_0/system_phaseDetector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_phaseDetector_0_0 || ORIG_REF_NAME==system_phaseDetector_0_0} -quiet] -quiet

# IP: bd/system/ip/system_NCO_0_0/system_NCO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_NCO_0_0 || ORIG_REF_NAME==system_NCO_0_0} -quiet] -quiet

# IP: bd/system/ip/system_positive_offset_0/system_positive_offset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_positive_offset_0 || ORIG_REF_NAME==system_positive_offset_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_15/system_xlslice_0_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_15 || ORIG_REF_NAME==system_xlslice_0_15} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_16/system_xlslice_0_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_16 || ORIG_REF_NAME==system_xlslice_0_16} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_1_0/system_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_1_0 || ORIG_REF_NAME==system_xlslice_1_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_17/system_xlslice_0_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_17 || ORIG_REF_NAME==system_xlslice_0_17} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_18/system_xlslice_0_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_18 || ORIG_REF_NAME==system_xlslice_0_18} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_1_1/system_xlslice_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_1_1 || ORIG_REF_NAME==system_xlslice_1_1} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_2_0/system_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_2_0 || ORIG_REF_NAME==system_xlslice_2_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_3_0/system_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_3_0 || ORIG_REF_NAME==system_xlslice_3_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_19/system_xlslice_0_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_19 || ORIG_REF_NAME==system_xlslice_0_19} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_1_2/system_xlslice_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_1_2 || ORIG_REF_NAME==system_xlslice_1_2} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_2_1/system_xlslice_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_2_1 || ORIG_REF_NAME==system_xlslice_2_1} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_3_1/system_xlslice_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_3_1 || ORIG_REF_NAME==system_xlslice_3_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: bd/system/system_ooc.xdc
