# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/tandeitnik/Documents/GitHub/vivadoProjects/cfg/clocks.xdc

# XDC: C:/Users/tandeitnik/Documents/GitHub/vivadoProjects/cfg/ports.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ds_buf_1_0 || ORIG_REF_NAME==system_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_2_0/system_util_ds_buf_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ds_buf_2_0 || ORIG_REF_NAME==system_util_ds_buf_2_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_red_pitaya_adc_0_0/system_axis_red_pitaya_adc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_adc_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_adc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_red_pitaya_dac_0_0/system_axis_red_pitaya_dac_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_dac_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_dac_0_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_0/system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_125M_0/system_rst_ps7_0_125M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_125M_0 || ORIG_REF_NAME==system_rst_ps7_0_125M_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_0/system_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_0 || ORIG_REF_NAME==system_xlconstant_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_cfg_register_0_0/system_axi_cfg_register_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_cfg_register_0_0 || ORIG_REF_NAME==system_axi_cfg_register_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_1/system_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_1 || ORIG_REF_NAME==system_xlconstant_0_1} -quiet] -quiet

# IP: bd/system/ip/system_LF_LFSR_4bit_1_3/system_LF_LFSR_4bit_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LF_LFSR_4bit_1_3 || ORIG_REF_NAME==system_LF_LFSR_4bit_1_3} -quiet] -quiet

# IP: bd/system/ip/system_LF_LFSR_4bit_2_3/system_LF_LFSR_4bit_2_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LF_LFSR_4bit_2_3 || ORIG_REF_NAME==system_LF_LFSR_4bit_2_3} -quiet] -quiet

# IP: bd/system/ip/system_LF_LFSR_4bit_3_3/system_LF_LFSR_4bit_3_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LF_LFSR_4bit_3_3 || ORIG_REF_NAME==system_LF_LFSR_4bit_3_3} -quiet] -quiet

# IP: bd/system/ip/system_LF_LFSR_1bit_0_4/system_LF_LFSR_1bit_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LF_LFSR_1bit_0_4 || ORIG_REF_NAME==system_LF_LFSR_1bit_0_4} -quiet] -quiet

# IP: bd/system/ip/system_LF_LFSR_4bit_0_8/system_LF_LFSR_4bit_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LF_LFSR_4bit_0_8 || ORIG_REF_NAME==system_LF_LFSR_4bit_0_8} -quiet] -quiet

# IP: bd/system/ip/system_LF_LFSR_8bit_0_4/system_LF_LFSR_8bit_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LF_LFSR_8bit_0_4 || ORIG_REF_NAME==system_LF_LFSR_8bit_0_4} -quiet] -quiet

# IP: bd/system/ip/system_addressSelector_0_0/system_addressSelector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_addressSelector_0_0 || ORIG_REF_NAME==system_addressSelector_0_0} -quiet] -quiet

# IP: bd/system/ip/system_ROM_fValues_0_4/system_ROM_fValues_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ROM_fValues_0_4 || ORIG_REF_NAME==system_ROM_fValues_0_4} -quiet] -quiet

# IP: bd/system/ip/system_ROM_gValues_0_4/system_ROM_gValues_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ROM_gValues_0_4 || ORIG_REF_NAME==system_ROM_gValues_0_4} -quiet] -quiet

# IP: bd/system/ip/system_boxMullerMultiplier_0_4/system_boxMullerMultiplier_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_boxMullerMultiplier_0_4 || ORIG_REF_NAME==system_boxMullerMultiplier_0_4} -quiet] -quiet

# IP: bd/system/ip/system_LF_LFSR_4bit_1_4/system_LF_LFSR_4bit_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LF_LFSR_4bit_1_4 || ORIG_REF_NAME==system_LF_LFSR_4bit_1_4} -quiet] -quiet

# IP: bd/system/ip/system_LF_LFSR_4bit_2_4/system_LF_LFSR_4bit_2_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LF_LFSR_4bit_2_4 || ORIG_REF_NAME==system_LF_LFSR_4bit_2_4} -quiet] -quiet

# IP: bd/system/ip/system_LF_LFSR_4bit_3_4/system_LF_LFSR_4bit_3_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LF_LFSR_4bit_3_4 || ORIG_REF_NAME==system_LF_LFSR_4bit_3_4} -quiet] -quiet

# IP: bd/system/ip/system_LF_LFSR_1bit_0_5/system_LF_LFSR_1bit_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LF_LFSR_1bit_0_5 || ORIG_REF_NAME==system_LF_LFSR_1bit_0_5} -quiet] -quiet

# IP: bd/system/ip/system_LF_LFSR_4bit_0_9/system_LF_LFSR_4bit_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LF_LFSR_4bit_0_9 || ORIG_REF_NAME==system_LF_LFSR_4bit_0_9} -quiet] -quiet

# IP: bd/system/ip/system_LF_LFSR_8bit_0_5/system_LF_LFSR_8bit_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LF_LFSR_8bit_0_5 || ORIG_REF_NAME==system_LF_LFSR_8bit_0_5} -quiet] -quiet

# IP: bd/system/ip/system_addressSelector_0_1/system_addressSelector_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_addressSelector_0_1 || ORIG_REF_NAME==system_addressSelector_0_1} -quiet] -quiet

# IP: bd/system/ip/system_boxMullerMultiplier_0_5/system_boxMullerMultiplier_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_boxMullerMultiplier_0_5 || ORIG_REF_NAME==system_boxMullerMultiplier_0_5} -quiet] -quiet

# IP: bd/system/ip/system_LF_LFSR_4bit_1_5/system_LF_LFSR_4bit_1_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LF_LFSR_4bit_1_5 || ORIG_REF_NAME==system_LF_LFSR_4bit_1_5} -quiet] -quiet

# IP: bd/system/ip/system_LF_LFSR_4bit_2_5/system_LF_LFSR_4bit_2_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LF_LFSR_4bit_2_5 || ORIG_REF_NAME==system_LF_LFSR_4bit_2_5} -quiet] -quiet

# IP: bd/system/ip/system_LF_LFSR_4bit_3_5/system_LF_LFSR_4bit_3_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LF_LFSR_4bit_3_5 || ORIG_REF_NAME==system_LF_LFSR_4bit_3_5} -quiet] -quiet

# IP: bd/system/ip/system_LF_LFSR_1bit_0_6/system_LF_LFSR_1bit_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LF_LFSR_1bit_0_6 || ORIG_REF_NAME==system_LF_LFSR_1bit_0_6} -quiet] -quiet

# IP: bd/system/ip/system_LF_LFSR_4bit_0_10/system_LF_LFSR_4bit_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LF_LFSR_4bit_0_10 || ORIG_REF_NAME==system_LF_LFSR_4bit_0_10} -quiet] -quiet

# IP: bd/system/ip/system_LF_LFSR_8bit_0_6/system_LF_LFSR_8bit_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LF_LFSR_8bit_0_6 || ORIG_REF_NAME==system_LF_LFSR_8bit_0_6} -quiet] -quiet

# IP: bd/system/ip/system_addressSelector_0_2/system_addressSelector_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_addressSelector_0_2 || ORIG_REF_NAME==system_addressSelector_0_2} -quiet] -quiet

# IP: bd/system/ip/system_boxMullerMultiplier_1_0/system_boxMullerMultiplier_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_boxMullerMultiplier_1_0 || ORIG_REF_NAME==system_boxMullerMultiplier_1_0} -quiet] -quiet

# IP: bd/system/ip/system_LF_LFSR_4bit_1_6/system_LF_LFSR_4bit_1_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LF_LFSR_4bit_1_6 || ORIG_REF_NAME==system_LF_LFSR_4bit_1_6} -quiet] -quiet

# IP: bd/system/ip/system_LF_LFSR_4bit_2_6/system_LF_LFSR_4bit_2_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LF_LFSR_4bit_2_6 || ORIG_REF_NAME==system_LF_LFSR_4bit_2_6} -quiet] -quiet

# IP: bd/system/ip/system_LF_LFSR_4bit_3_6/system_LF_LFSR_4bit_3_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LF_LFSR_4bit_3_6 || ORIG_REF_NAME==system_LF_LFSR_4bit_3_6} -quiet] -quiet

# IP: bd/system/ip/system_LF_LFSR_1bit_0_7/system_LF_LFSR_1bit_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LF_LFSR_1bit_0_7 || ORIG_REF_NAME==system_LF_LFSR_1bit_0_7} -quiet] -quiet

# IP: bd/system/ip/system_LF_LFSR_4bit_0_11/system_LF_LFSR_4bit_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LF_LFSR_4bit_0_11 || ORIG_REF_NAME==system_LF_LFSR_4bit_0_11} -quiet] -quiet

# IP: bd/system/ip/system_LF_LFSR_8bit_0_7/system_LF_LFSR_8bit_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LF_LFSR_8bit_0_7 || ORIG_REF_NAME==system_LF_LFSR_8bit_0_7} -quiet] -quiet

# IP: bd/system/ip/system_addressSelector_0_3/system_addressSelector_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_addressSelector_0_3 || ORIG_REF_NAME==system_addressSelector_0_3} -quiet] -quiet

# IP: bd/system/ip/system_boxMullerMultiplier_2_0/system_boxMullerMultiplier_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_boxMullerMultiplier_2_0 || ORIG_REF_NAME==system_boxMullerMultiplier_2_0} -quiet] -quiet

# IP: bd/system/ip/system_boxMullerAdder_0_1/system_boxMullerAdder_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_boxMullerAdder_0_1 || ORIG_REF_NAME==system_boxMullerAdder_0_1} -quiet] -quiet

# IP: bd/system/ip/system_util_reduced_logic_0_0/system_util_reduced_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_reduced_logic_0_0 || ORIG_REF_NAME==system_util_reduced_logic_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_1/system_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_1 || ORIG_REF_NAME==system_xlconcat_0_1} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_2/system_xlconcat_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_2 || ORIG_REF_NAME==system_xlconcat_0_2} -quiet] -quiet

# IP: bd/system/ip/system_util_reduced_logic_0_1/system_util_reduced_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_reduced_logic_0_1 || ORIG_REF_NAME==system_util_reduced_logic_0_1} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_3/system_xlconcat_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_3 || ORIG_REF_NAME==system_xlconcat_0_3} -quiet] -quiet

# IP: bd/system/ip/system_util_reduced_logic_0_2/system_util_reduced_logic_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_reduced_logic_0_2 || ORIG_REF_NAME==system_util_reduced_logic_0_2} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_4/system_xlconcat_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_4 || ORIG_REF_NAME==system_xlconcat_0_4} -quiet] -quiet

# IP: bd/system/ip/system_util_reduced_logic_0_3/system_util_reduced_logic_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_reduced_logic_0_3 || ORIG_REF_NAME==system_util_reduced_logic_0_3} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_3/system_xlconstant_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_3 || ORIG_REF_NAME==system_xlconstant_0_3} -quiet] -quiet

# IP: bd/system/ip/system_gainBrown_1/system_gainBrown_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_gainBrown_1 || ORIG_REF_NAME==system_gainBrown_1} -quiet] -quiet

# IP: bd/system/ip/system_gainWhite_0_0/system_gainWhite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_gainWhite_0_0 || ORIG_REF_NAME==system_gainWhite_0_0} -quiet] -quiet

# IP: bd/system/ip/system_signal_split_0_0_2/system_signal_split_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_signal_split_0_0 || ORIG_REF_NAME==system_signal_split_0_0} -quiet] -quiet

# IP: bd/system/ip/system_outputCalibration_0_0/system_outputCalibration_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_outputCalibration_0_0 || ORIG_REF_NAME==system_outputCalibration_0_0} -quiet] -quiet

# IP: bd/system/ip/system_outputCalibration_A_0/system_outputCalibration_A_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_outputCalibration_A_0 || ORIG_REF_NAME==system_outputCalibration_A_0} -quiet] -quiet

# IP: bd/system/ip/system_decimator_0_0/system_decimator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_decimator_0_0 || ORIG_REF_NAME==system_decimator_0_0} -quiet] -quiet

# IP: bd/system/ip/system_biquadFilter_0_0/system_biquadFilter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_biquadFilter_0_0 || ORIG_REF_NAME==system_biquadFilter_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_7/system_xlslice_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_7 || ORIG_REF_NAME==system_xlslice_0_7} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_8/system_xlslice_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_8 || ORIG_REF_NAME==system_xlslice_0_8} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_9/system_xlslice_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_9 || ORIG_REF_NAME==system_xlslice_0_9} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_10/system_xlslice_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_10 || ORIG_REF_NAME==system_xlslice_0_10} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_11/system_xlslice_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_11 || ORIG_REF_NAME==system_xlslice_0_11} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_12/system_xlslice_0_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_12 || ORIG_REF_NAME==system_xlslice_0_12} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_4/system_xlconstant_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_4 || ORIG_REF_NAME==system_xlconstant_0_4} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: bd/system/system_ooc.xdc
