@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Feb 19 15:57:45 -0300 2024
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim rndGaussGen2_TB_behav -key {Behavioral:sim_1:Functional:rndGaussGen2_TB} -tclbatch rndGaussGen2_TB.tcl -protoinst "protoinst_files/system.protoinst" -view C:/Users/tandeitnik/Documents/redpitaya_guide-master/tmp/cores/randomGaussianGenerator/rndGaussGen_TB_behav.wcfg -log simulate.log"
call xsim  rndGaussGen2_TB_behav -key {Behavioral:sim_1:Functional:rndGaussGen2_TB} -tclbatch rndGaussGen2_TB.tcl -protoinst "protoinst_files/system.protoinst" -view C:/Users/tandeitnik/Documents/redpitaya_guide-master/tmp/cores/randomGaussianGenerator/rndGaussGen_TB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
