# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/tandeitnik/Documents/GitHub/vivadoProjects/cfg/clocks.xdc

# XDC: C:/Users/tandeitnik/Documents/GitHub/vivadoProjects/cfg/ports.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ds_buf_1_0 || ORIG_REF_NAME==system_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_2_0/system_util_ds_buf_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ds_buf_2_0 || ORIG_REF_NAME==system_util_ds_buf_2_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_red_pitaya_adc_0_0/system_axis_red_pitaya_adc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_adc_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_adc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_red_pitaya_dac_0_0/system_axis_red_pitaya_dac_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_dac_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_dac_0_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_0/system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_125M_0/system_rst_ps7_0_125M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_125M_0 || ORIG_REF_NAME==system_rst_ps7_0_125M_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_0/system_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_0 || ORIG_REF_NAME==system_xlconstant_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_cfg_register_0_0/system_axi_cfg_register_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_cfg_register_0_0 || ORIG_REF_NAME==system_axi_cfg_register_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_1/system_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_1 || ORIG_REF_NAME==system_xlconstant_0_1} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_7/system_xlslice_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_7 || ORIG_REF_NAME==system_xlslice_0_7} -quiet] -quiet

# IP: bd/system/ip/system_dat_CHA_0/system_dat_CHA_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dat_CHA_0 || ORIG_REF_NAME==system_dat_CHA_0} -quiet] -quiet

# IP: bd/system/ip/system_outputCalibration_0_0/system_outputCalibration_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_outputCalibration_0_0 || ORIG_REF_NAME==system_outputCalibration_0_0} -quiet] -quiet

# IP: bd/system/ip/system_outputCalibration_A_0/system_outputCalibration_A_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_outputCalibration_A_0 || ORIG_REF_NAME==system_outputCalibration_A_0} -quiet] -quiet

# IP: bd/system/ip/system_inputCalibration_0_0/system_inputCalibration_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_inputCalibration_0_0 || ORIG_REF_NAME==system_inputCalibration_0_0} -quiet] -quiet

# IP: bd/system/ip/system_inputCalibration_A_0/system_inputCalibration_A_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_inputCalibration_A_0 || ORIG_REF_NAME==system_inputCalibration_A_0} -quiet] -quiet

# IP: bd/system/ip/system_decimator_DualChannel_0_0/system_decimator_DualChannel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_decimator_DualChannel_0_0 || ORIG_REF_NAME==system_decimator_DualChannel_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_9/system_xlslice_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_9 || ORIG_REF_NAME==system_xlslice_0_9} -quiet] -quiet

# IP: bd/system/ip/system_inIntCorrCHA_0/system_inIntCorrCHA_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_inIntCorrCHA_0 || ORIG_REF_NAME==system_inIntCorrCHA_0} -quiet] -quiet

# IP: bd/system/ip/system_intCorrCHA_0/system_intCorrCHA_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_intCorrCHA_0 || ORIG_REF_NAME==system_intCorrCHA_0} -quiet] -quiet

# IP: bd/system/ip/system_inSlpCorrCHA_0/system_inSlpCorrCHA_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_inSlpCorrCHA_0 || ORIG_REF_NAME==system_inSlpCorrCHA_0} -quiet] -quiet

# IP: bd/system/ip/system_outIntCorrCHA_0/system_outIntCorrCHA_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_outIntCorrCHA_0 || ORIG_REF_NAME==system_outIntCorrCHA_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_10/system_xlslice_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_10 || ORIG_REF_NAME==system_xlslice_0_10} -quiet] -quiet

# IP: bd/system/ip/system_outIntCorrCHA_1/system_outIntCorrCHA_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_outIntCorrCHA_1 || ORIG_REF_NAME==system_outIntCorrCHA_1} -quiet] -quiet

# IP: bd/system/ip/system_outIntCorrCHA_2/system_outIntCorrCHA_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_outIntCorrCHA_2 || ORIG_REF_NAME==system_outIntCorrCHA_2} -quiet] -quiet

# IP: bd/system/ip/system_delay_0_0/system_delay_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_delay_0_0 || ORIG_REF_NAME==system_delay_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_14/system_xlslice_0_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_14 || ORIG_REF_NAME==system_xlslice_0_14} -quiet] -quiet

# IP: bd/system/ip/system_blk_mem_gen_0_0/system_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_blk_mem_gen_0_0 || ORIG_REF_NAME==system_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_2/system_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_2 || ORIG_REF_NAME==system_xlconstant_0_2} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_3/system_xlconstant_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_3 || ORIG_REF_NAME==system_xlconstant_0_3} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_15/system_xlslice_0_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_15 || ORIG_REF_NAME==system_xlslice_0_15} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_1_0/system_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_1_0 || ORIG_REF_NAME==system_xlslice_1_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_16/system_xlslice_0_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_16 || ORIG_REF_NAME==system_xlslice_0_16} -quiet] -quiet

# IP: bd/system/ip/system_biquadFilter_0_0/system_biquadFilter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_biquadFilter_0_0 || ORIG_REF_NAME==system_biquadFilter_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gain_0_0/system_gain_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_gain_0_0 || ORIG_REF_NAME==system_gain_0_0} -quiet] -quiet

# IP: bd/system/ip/system_biquadGain_2/system_biquadGain_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_biquadGain_2 || ORIG_REF_NAME==system_biquadGain_2} -quiet] -quiet

# IP: bd/system/ip/system_biquadGain_0/system_biquadGain_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_biquadGain_0 || ORIG_REF_NAME==system_biquadGain_0} -quiet] -quiet

# IP: bd/system/ip/system_biquadGain_3/system_biquadGain_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_biquadGain_3 || ORIG_REF_NAME==system_biquadGain_3} -quiet] -quiet

# IP: bd/system/ip/system_biquadGain_4/system_biquadGain_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_biquadGain_4 || ORIG_REF_NAME==system_biquadGain_4} -quiet] -quiet

# IP: bd/system/ip/system_biquadGain_5/system_biquadGain_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_biquadGain_5 || ORIG_REF_NAME==system_biquadGain_5} -quiet] -quiet

# IP: bd/system/ip/system_biquadGain_1/system_biquadGain_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_biquadGain_1 || ORIG_REF_NAME==system_biquadGain_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: bd/system/system_ooc.xdc
