# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/tandeitnik/Documents/GitHub/vivadoProjects/projects/sine_generator/sine_generator.srcs/sources_1/bd/system/ip/system_blk_mem_gen_1_0/system_blk_mem_gen_1_0.xci
# IP: The module: 'system_blk_mem_gen_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tandeitnik/Documents/GitHub/vivadoProjects/projects/sine_generator/sine_generator.srcs/sources_1/bd/system/ip/system_blk_mem_gen_1_0/system_blk_mem_gen_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_blk_mem_gen_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/tandeitnik/Documents/GitHub/vivadoProjects/projects/sine_generator/sine_generator.srcs/sources_1/bd/system/ip/system_blk_mem_gen_1_0/system_blk_mem_gen_1_0.xci
# IP: The module: 'system_blk_mem_gen_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tandeitnik/Documents/GitHub/vivadoProjects/projects/sine_generator/sine_generator.srcs/sources_1/bd/system/ip/system_blk_mem_gen_1_0/system_blk_mem_gen_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_blk_mem_gen_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
